### ISSUE TITLE
The form is reset after `Validade` when using a custom form

### ISSUE THREAD

**Issue by anitacaron** [ontodev/nanobot.rs#78]
When using a custom form, the form is changed to the default after pressing the' Validate' button.

**Comment by jamesaoverton** [comment]
Sorry, I can't replicate this. I also tried it on your DROID instance for a table using "ols_form", and "Validate" took me back to "ols_form". Can you show me on a call, or something?

**Comment by anitacaron** [comment]
The address is the same, but the elements in the form change. For example, the autocomplete is gone.

The form before clicking on Validate. Note the message "Search for ontology entity" is where the autocomplete is present.

![Screenshot 2024-03-20 at 09 04 23](https://github.com/ontodev/nanobot.rs/assets/2208124/db84862d-f2cd-43cb-bdfe-3204f9ed1ad1)

The form after. The message is gone and all other modifications (route field was read-only)

![Screenshot 2024-03-20 at 09 10 36](https://github.com/ontodev/nanobot.rs/assets/2208124/431a617c-8fd6-4659-9cb0-da9869e1365a)

**Comment by jamesaoverton** [comment]
Ok, I can replicate this, but only when adding a row, not when editing an existing row. I'll look into it.

**Comment by anitacaron** [comment]
When editing a row, I removed the route_label, and I could see the "Search for ontology entity", but after clicking on Validate, the route is no longer read-only and no autocomplete.

![Screenshot 2024-03-20 at 17 24 22](https://github.com/ontodev/nanobot.rs/assets/2208124/8cf41b4d-0257-4ffb-a693-a59831acf2fc)

**Comment by jamesaoverton** [comment]
I got very confused trying to reproduce this. You were right. I think I fixed it in #81. I plan to release new binaries later today, so you can try it out.
