### ISSUE TITLE
Add GitHub Action to test and compile binaries

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/nanobot.rs#8]
It would be nice to attach binaries for at least Linux to the GitHub Action results, but I'm still not sure the best way to do this.

As I said in #7, I'm starting to think that a plain GitHub Action calling a `make test` is better than a fancy custom GitHub Action. One benefit is that you can run `make` locally, while it's hard to replicate a GitHub Action environment. Debugging GitHub Actions is particularly painful.

**Comment by ckindermann** [comment]
There are GitHub Actions for comparing the output of command line calls with text files, e.g., [this](https://github.com/marketplace/actions/assert-command-line-output). I haven't found one that actually works yet.
