### ISSUE TITLE
CGI custom stylesheet loading issue 

### ISSUE THREAD

**Issue by bicantester** [ontodev/nanobot.rs#90]
**Problem:**
In my project, I use a [custom css file](https://github.com/Cellular-Semantics/human-neocortex-non-neuronal-cells/blob/main/src/assets/bstreeview.css) located in the `src/assets` folder. This file is referenced in [one of my templates](https://github.com/Cellular-Semantics/human-neocortex-non-neuronal-cells/blob/be9893fdc16e5f6b5b33564dc6f28c019d96f357/src/resources/taxonomy_view.html#L7) as follows:

```html
<link rel="stylesheet" href="{{ page.root }}assets/bstreeview.css" />
```

Previously, when running the project with Nanobot's `serve` mode, the CSS file loaded and worked as expected. However, after switching to use Nanobot in CGI mode, the CSS file no longer works.

**Debug experiments:** 

- The browser's developer tools show that the CSS file is loaded successfully.
<img width="1043" alt="image" src="https://github.com/user-attachments/assets/3d685cda-c9c3-4a18-87f8-ad780c1a8877">

- JavaScript files imported in a similar way continue to work without any issues:
```html
<script src="{{ page.root }}assets/bstreeview.js"></script>
```

- When I serve the same CSS file via a CDN, it works as expected:
```html
<link rel="stylesheet" href="http://cdn.jsdelivr.net/gh/Cellular-Semantics/human-neocortex-non-neuronal-cells/src/assets/bstreeview.css"/>
```

The issue might be related to the `Content-Type` response headers. Here's a comparison of Content-Type values from different sources:

- `Content-Type` of CGI mode: `text/html; charset=utf-8, text/css`
- `Content-Type` of  serve mode: `text/css `
- `Content-Type` of  CDN: `text/css; charset=utf-8`

PS: sorry, I accidentally posted with my test account. This is @hkir-dev

**Comment by hkir-dev** [comment]
This issue occurs in Chrome v131 and Safari 18.1.1. Interestingly, the CSS renders correctly in Firefox v132.

**Comment by bicantester** [comment]
Flask was adding default headers, which caused the issue. Clearing those headers and using the headers provided by Nanobot CGI resolved the problem.
